# Generated by Django 6.0 on 2025-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('note', 'Nota'), ('reminder', 'recordatorio')], default='note', max_length=20)),
                ('reminder_datetime', models.DateTimeField(blank=True, help_text='Fecha/hora del recordatorio (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
