# Generated by Django 6.0 on 2025-12-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
